### ISSUE TITLE
Missing Map

### ISSUE THREAD

**Issue by michael-77** [laurakwriting/john-muir_my-first-summer-in-the-sierra#8]
What was the rationale for not including the map of Yosemite National Park?
Was it a feature of a later edition or did you feel it wasn't actually essential to the book?

**Comment by laurakwriting** [comment]
Thank you for all your feedback Michael, much appreciated!

Here's some background and a suggestion to address the missing map issue you noted -

I excluded the map because the HathiTrust page scans did not include a map of Yosemite National Park. Also, I could not find the USGS map that was in PG to verify its source. Finally, I thought the quality of the PG image was not of high enough quality to use anyway.

That said, I do think it would be nice to include a map, so here is what I suggest doing ... 

I have now located another (similar) USGS map of Yosemite that was published in 1909 (making it the newest map of Yosemite that was available at the time of publication for this book, which was 1917).

As far as I am aware, USGS maps are all in the public domain regardless of date (because they are produced by US government); but this particular situation, the map scan is old enough to be public domain anyway - as it was produced in 1909. 

Here is the download page for the map I plan to use: https://store.usgs.gov/product/525211

Does that all sound like a good solution? If so I'll go ahead and create a greyscale version and include at the end of chapter 11.

Thanks!
Laura

**Comment by michael-77** [comment]
That all sounds very reasonable. 

It would be beyond me with my limited Photoshop skills but keeping the brown and blue colours while eliminating the yellowish background colour would be more desirable than a gray-scale rendering of the map. (In fact, I would find a colour image with the yellowish background left intact preferable to a gray-scale one.)

**Comment by michael-77** [comment]
Lovely map by the way. Something really nice about all those contour lines.

**Comment by laurakwriting** [comment]
Sounds good, it is a very nice scan that retains the historic "look" of the map (while still being high quality). I'll give the color option a try, I agree it would be very nice if I can get it right. Thanks!

**Comment by laurakwriting** [comment]
Does this look acceptable:

![yosemite-usgs-map](https://user-images.githubusercontent.com/6282744/70180450-4914d500-169d-11ea-8613-9433822d8311.jpg)

**Comment by michael-77** [comment]
I'm struggling to read the place names when I zoom in so I think it needs to be processed with a higher resolution from the original pdf where I could read them.

**Comment by laurakwriting** [comment]
OK, good to know. I'll try a few adjustments. Thanks!

**Comment by laurakwriting** [comment]
Here is a larger image (4872px x 5945px) which provides much more detail but it also has a significantly larger file size (4.6MB):

![yosemite-usgs-map](https://user-images.githubusercontent.com/6282744/70200849-07525180-16d2-11ea-8c8e-0330fa536825.jpg)

**Comment by laurakwriting** [comment]
I've now added a high-quality map that can be read when zoomed, please see:
- 6cdbdf7 Add map of Yosemite

**Comment by laurakwriting** [comment]
One more change coming soon - Alex asked that the perimeter of the map be cleaned up a bit more, so I'll do that now. I hope to retain the scale and declination symbols below the map, but I'll try to remove the various "file copy" type stamps.

**Comment by laurakwriting** [comment]
The revised map has now been committed. Please see:
- 447e241 More restoration work on the map of Yosemite

**Comment by michael-77** [comment]
Really nice job on the map.

Any chance you could put the original jpg in as `images/yosemite-usgs-map.source.jpg` in case we are able to do further svg (or other) processing in future.

**Comment by laurakwriting** [comment]
Sure, happy too! JPG source of map now here:
- 12e466c Adds Yosemite map source JPG
